"""
Generate a human-reviewable "expected output" file from a function's
actual output over a list of sample cases.

Not specific to attacks or to any single pipeline stage: the case list
and the compute function are both passed in, so the same tool is meant
to be reused for future conversion pipelines (feats, spells, special
qualities...) that need the same workflow:

1. Run this once against real sample data to capture the current output.
2. A human reviews and hand-corrects the generated file.
3. The corrected file is committed and used as a regression fixture in
   tests (current output must keep matching it).

The generated file is a starting point, not a trusted fixture — it must
be reviewed before it is relied upon in a test.

to_plain() (the generic dataclass/enum flattener used to build the
result before writing it out) lives in monsterforge.serialization.plain_data,
not here: this test-tooling module reuses it, but it must not itself be
imported by monsterforge/ source code (tests/ depends on monsterforge/,
never the other way around).
"""
import pprint
from pathlib import Path
from typing import Callable
from monsterforge.serialization.plain_data import to_plain


def generate_expected_outputs(
        cases: list[dict],
        compute_fn: Callable[[dict], object],
        output_path: Path,
        variable_name: str = "EXPECTED_OUTPUTS") -> None:
    """
    Run compute_fn over each case and write the results as a plain-data
    Python literal to output_path, ready for human review.

    Args:
        cases: Sample input dicts (e.g. SAMPLE_ATTACKS).
        compute_fn: Called once per case, receiving that case's dict.
        output_path: Where to write the generated file.
        variable_name: Name of the top-level list assigned in the file.
    """
    results = [to_plain(compute_fn(case)) for case in cases]

    header = (
        '"""\n'
        "AUTO-GENERATED by tests/tools/generate_expected_outputs.py — "
        "NOT YET VALIDATED.\n\n"
        "Review each entry by hand against its corresponding input case\n"
        "before trusting this file as a regression fixture.\n"
        '"""\n\n'
    )
    body = f"{variable_name} = {pprint.pformat(results, width=88, sort_dicts=False)}\n"

    output_path.write_text(header + body)
