"""
TEMPLATE DI ATTACK [RAW]
name: str # e.g. "Shortbow"
modifier: str # e.g. "+8"
attack_type: str # e.g. "ranged" 
attack_effect: str # raw effect/damage portion, including extracted or referenced effects
"""

SAMPLE_ATTACKS = [
    {
        "name": "Tentacle",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "1d6+8 plus slime",
    },
    {
        "name": "Claw",
        "modifier": "+9",
        "attack_type": "melee",
        "attack_effect": "2d6+4",
    },
    {
        "name": "Incorporeal touch",
        "modifier": "+3",
        "attack_type": "melee",
        "attack_effect": "1d4 Wisdom drain",
    },
    {
        "name": "Bite",
        "modifier": "+5",
        "attack_type": "melee",
        "attack_effect": "1d6 plus poison",
    },
    {
        "name": "Web",
        "modifier": "+5",
        "attack_type": "ranged",
        "attack_effect": "",
    },
    {
        "name": "Light ray",
        "modifier": "+2",
        "attack_type": "ranged touch",
        "attack_effect": "1d6",
    },
    {
        "name": "Electricity ray",
        "modifier": "+9",
        "attack_type": "ranged touch",
        "attack_effect": "2d6",
    },
    {
        "name": "Bite",
        "modifier": "+9",
        "attack_type": "melee",
        "attack_effect": "1d6+1",
    },
    {
        "name": "Morningstar",
        "modifier": "+16",
        "attack_type": "melee",
        "attack_effect": "3d6+8",
    },
    {
        "name": "Rock",
        "modifier": "+9",
        "attack_type": "ranged",
        "attack_effect": "2d6+8",
    },
    {
        "name": "Warhammer",
        "modifier": "+3",
        "attack_type": "melee",
        "attack_effect": "1d8+1/×3 plus 1 fire",
    },
    {
        "name": "Shortspear",
        "modifier": "+3",
        "attack_type": "ranged",
        "attack_effect": "1d6+1 plus 1 fire",
    },
    {
        "name": "Slam",
        "modifier": "+6",
        "attack_type": "melee",
        "attack_effect": "1d8+1",
    },
    {
        "name": "Claw",
        "modifier": "+10",
        "attack_type": "melee",
        "attack_effect": "1d3+2 plus corporeal instability",
    },
    {
        "name": "Tentacle",
        "modifier": "+6",
        "attack_type": "melee",
        "attack_effect": "1d3+3",
    },
    {
        "name": "Bite",
        "modifier": "+9",
        "attack_type": "melee",
        "attack_effect": "1d4-2 plus petrification",
    },
    {
        "name": "Bite",
        "modifier": "+19",
        "attack_type": "melee",
        "attack_effect": "2d6+9 plus poison",
    },
    {
        "name": "Web",
        "modifier": "+11",
        "attack_type": "ranged",
        "attack_effect": "",
    },
    {
        "name": "Claw",
        "modifier": "+9",
        "attack_type": "melee",
        "attack_effect": "1d6+4",
    },
    {
        "name": "Claw",
        "modifier": "+18",
        "attack_type": "melee",
        "attack_effect": "2d8+6 plus fear",
    },
    {
        "name": "Slam",
        "modifier": "+6",
        "attack_type": "melee",
        "attack_effect": "1d6+1 plus 1d6 fire",
    },
    {
        "name": "Slam",
        "modifier": "+8",
        "attack_type": "melee",
        "attack_effect": "1d8+7",
    },
    {
        "name": "Morningstar",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "2d6+6",
    },
    {
        "name": "Javelin",
        "modifier": "+5",
        "attack_type": "ranged",
        "attack_effect": "1d8+6",
    },
    {},
    {
        "name": "Bite",
        "modifier": "+2",
        "attack_type": "melee",
        "attack_effect": "1d6+1 plus paralysis",
    },
    {
        "name": "Greatclub",
        "modifier": "+17",
        "attack_type": "melee",
        "attack_effect": "2d8+12",
    },
    {
        "name": "Slam",
        "modifier": "+17",
        "attack_type": "melee",
        "attack_effect": "1d4+8",
    },
    {
        "name": "Rock",
        "modifier": "+11",
        "attack_type": "ranged",
        "attack_effect": "2d8+12",
    },
    {
        "name": "Bite",
        "modifier": "+6",
        "attack_type": "melee",
        "attack_effect": "1d10+3",
    },
    {
        "name": "Tentacle",
        "modifier": "+28",
        "attack_type": "melee",
        "attack_effect": "2d8+12/19-20",
    },
    {
        "name": "Touch",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "1d4 Wisdom drain",
    },
    {
        "name": "Dagger",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "1d6+4/19-20",
    },
    {
        "name": "Claw",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "1d4+4",
    },
    {
        "name": "Burning touch",
        "modifier": "+4",
        "attack_type": "melee touch",
        "attack_effect": "1d8 fire plus combustion",
    },
    {
        "name": "Slam",
        "modifier": "+4",
        "attack_type": "melee",
        "attack_effect": "1d3+3 plus combustion",
    },
    {
        "name": "Slam",
        "modifier": "+9",
        "attack_type": "melee",
        "attack_effect": "1d8+4",
    },
    {
        "name": "Slam",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "1d6+7",
    },
    {
        "name": "Tongue",
        "modifier": "+12",
        "attack_type": "melee touch",
        "attack_effect": "paralysis",
    },
    {
        "name": "Bite",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "2d6+6 plus disease",
    },
    {
        "name": "Slam",
        "modifier": "+8",
        "attack_type": "melee",
        "attack_effect": "2d6+4 plus 2d6 acid",
    },
    {
        "name": "Bite",
        "modifier": "+7",
        "attack_type": "melee",
        "attack_effect": "1d6+4 plus poison",
    },
    {
        "name": "Tail slap",
        "modifier": "+4",
        "attack_type": "melee",
        "attack_effect": "1d6+1 plus positive energy",
    },
    {
        "name": "Tail touch",
        "modifier": "+4",
        "attack_type": "melee touch",
        "attack_effect": "positive energy",
    },
    {
        "name": "Antennae touch",
        "modifier": "+3",
        "attack_type": "melee",
        "attack_effect": "rust",
    },
    {
        "name": "Incorporeal touch",
        "modifier": "+3",
        "attack_type": "melee",
        "attack_effect": "1d6 Str",
    },
    {
        "name": "Incorporeal touch",
        "modifier": "+6",
        "attack_type": "melee",
        "attack_effect": "1d8 plus energy drain",
    },
    {
        "name": "Short sword",
        "modifier": "+4",
        "attack_type": "melee",
        "attack_effect": "1d4-2/19-20",
    },
    {
        "name": "Light crossbow",
        "modifier": "+4",
        "attack_type": "ranged",
        "attack_effect": "1d6/19-20",
    },
    {
        "name": "Swarm",
        "modifier": "",
        "attack_type": "",
        "attack_effect": "2d6",
    },
    {
        "name": "Bite",
        "modifier": "+57",
        "attack_type": "melee",
        "attack_effect": "4d8+17/18-20/×3",
    },
    {
        "name": "Slam",
        "modifier": "+12",
        "attack_type": "melee",
        "attack_effect": "2d6+9",
    },
    {
        "name": "Bite",
        "modifier": "+7",
        "attack_type": "melee",
        "attack_effect": "1d6+4",
    },
    {
        "name": "Short sword",
        "modifier": "+7",
        "attack_type": "melee",
        "attack_effect": "1d6+2/19-20",
    },
    {
        "name": "Claw",
        "modifier": "+7",
        "attack_type": "melee",
        "attack_effect": "1d4+2",
    },
    {
        "name": "Longbow",
        "modifier": "+8",
        "attack_type": "ranged",
        "attack_effect": "1d8/×3",
    },
    {
        "name": "Slam",
        "modifier": "+2",
        "attack_type": "melee",
        "attack_effect": "1d6+1",
    },
    {
        "name": "Club",
        "modifier": "+2",
        "attack_type": "melee",
        "attack_effect": "1d6+1",
    },
    {
        "name": "Bite",
        "modifier": "+3",
        "attack_type": "melee",
        "attack_effect": "1d6+1",
    },
]